name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      KEYSTORE_FILE_NAME: ${{ secrets.KEYSTORE_FILE_NAME }}
      SUPPORT_FILE_NAME: ${{ secrets.SUPPORT_FILE_NAME }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Checkout Repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue -PconnectionString=$CONNECTION_STRING -PcontainerName=$CONTAINER_NAME -PkeyStoreFileName=$KEYSTORE_FILE_NAME -PsupportDocumentFilename=$SUPPORT_FILE_NAME

